// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player_api.dart';
import 'api/simple.dart';
import 'api/webdav_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1647169078;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_arkpulse',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<TrackInfo> crateApiPlayerApiAudioPlayerExtractRemoteTrackInfo({
    required String url,
    required String username,
    required String token,
  });

  Future<PlaybackDiagnostics> crateApiPlayerApiAudioPlayerGetDiagnostics();

  Future<PlaybackProgress> crateApiPlayerApiAudioPlayerGetProgress();

  Future<PlaybackState> crateApiPlayerApiAudioPlayerGetState();

  Future<TrackInfo> crateApiPlayerApiAudioPlayerGetTrackInfo();

  Future<void> crateApiPlayerApiAudioPlayerInitEngine();

  Future<AudioPlayer> crateApiPlayerApiAudioPlayerNew();

  Future<void> crateApiPlayerApiAudioPlayerPause();

  Future<void> crateApiPlayerApiAudioPlayerPlayLocalFile({
    required String path,
  });

  Future<void> crateApiPlayerApiAudioPlayerPlayRemoteFile({
    required String url,
    required String username,
    required String token,
  });

  Future<void> crateApiPlayerApiAudioPlayerResume();

  Future<void> crateApiPlayerApiAudioPlayerSeek({
    required PlatformInt64 positionMs,
  });

  Future<void> crateApiPlayerApiAudioPlayerStop();

  String crateApiWebdavApiWebDavClientAutoAccessorGetServerUrl({
    required WebDavClient that,
  });

  String crateApiWebdavApiWebDavClientAutoAccessorGetToken({
    required WebDavClient that,
  });

  String crateApiWebdavApiWebDavClientAutoAccessorGetUsername({
    required WebDavClient that,
  });

  void crateApiWebdavApiWebDavClientAutoAccessorSetServerUrl({
    required WebDavClient that,
    required String serverUrl,
  });

  void crateApiWebdavApiWebDavClientAutoAccessorSetToken({
    required WebDavClient that,
    required String token,
  });

  void crateApiWebdavApiWebDavClientAutoAccessorSetUsername({
    required WebDavClient that,
    required String username,
  });

  Future<List<WebDavEntry>> crateApiWebdavApiWebDavClientListAllAudioRecursive({
    required WebDavClient that,
    required String rootPath,
  });

  Future<List<WebDavEntry>> crateApiWebdavApiWebDavClientListDirectory({
    required WebDavClient that,
    required String path,
  });

  WebDavClient crateApiWebdavApiWebDavClientNew({
    required String serverUrl,
    required String username,
    required String token,
  });

  BigInt crateApiSimpleAdd({required BigInt left, required BigInt right});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioPlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioPlayer;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AudioPlayerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WebDavClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WebDavClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WebDavClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<TrackInfo> crateApiPlayerApiAudioPlayerExtractRemoteTrackInfo({
    required String url,
    required String username,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerExtractRemoteTrackInfoConstMeta,
        argValues: [url, username, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerApiAudioPlayerExtractRemoteTrackInfoConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_extract_remote_track_info",
        argNames: ["url", "username", "token"],
      );

  @override
  Future<PlaybackDiagnostics> crateApiPlayerApiAudioPlayerGetDiagnostics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_diagnostics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerGetDiagnosticsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerGetDiagnosticsConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_get_diagnostics",
        argNames: [],
      );

  @override
  Future<PlaybackProgress> crateApiPlayerApiAudioPlayerGetProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerGetProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerGetProgressConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_get_progress", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerApiAudioPlayerGetState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerGetStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerGetStateConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_get_state", argNames: []);

  @override
  Future<TrackInfo> crateApiPlayerApiAudioPlayerGetTrackInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerGetTrackInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerGetTrackInfoConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_get_track_info",
        argNames: [],
      );

  @override
  Future<void> crateApiPlayerApiAudioPlayerInitEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerInitEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerInitEngineConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_init_engine", argNames: []);

  @override
  Future<AudioPlayer> crateApiPlayerApiAudioPlayerNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerNewConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_new", argNames: []);

  @override
  Future<void> crateApiPlayerApiAudioPlayerPause() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_pause", argNames: []);

  @override
  Future<void> crateApiPlayerApiAudioPlayerPlayLocalFile({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerPlayLocalFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerPlayLocalFileConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_play_local_file",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiPlayerApiAudioPlayerPlayRemoteFile({
    required String url,
    required String username,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerPlayRemoteFileConstMeta,
        argValues: [url, username, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerPlayRemoteFileConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_play_remote_file",
        argNames: ["url", "username", "token"],
      );

  @override
  Future<void> crateApiPlayerApiAudioPlayerResume() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerResumeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerResumeConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_resume", argNames: []);

  @override
  Future<void> crateApiPlayerApiAudioPlayerSeek({
    required PlatformInt64 positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerSeekConstMeta,
        argValues: [positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerSeekConstMeta =>
      const TaskConstMeta(
        debugName: "AudioPlayer_seek",
        argNames: ["positionMs"],
      );

  @override
  Future<void> crateApiPlayerApiAudioPlayerStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerApiAudioPlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerApiAudioPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "AudioPlayer_stop", argNames: []);

  @override
  String crateApiWebdavApiWebDavClientAutoAccessorGetServerUrl({
    required WebDavClient that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiWebdavApiWebDavClientAutoAccessorGetServerUrlConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorGetServerUrlConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_get_server_url",
        argNames: ["that"],
      );

  @override
  String crateApiWebdavApiWebDavClientAutoAccessorGetToken({
    required WebDavClient that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWebdavApiWebDavClientAutoAccessorGetTokenConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorGetTokenConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_get_token",
        argNames: ["that"],
      );

  @override
  String crateApiWebdavApiWebDavClientAutoAccessorGetUsername({
    required WebDavClient that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiWebdavApiWebDavClientAutoAccessorGetUsernameConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorGetUsernameConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_get_username",
        argNames: ["that"],
      );

  @override
  void crateApiWebdavApiWebDavClientAutoAccessorSetServerUrl({
    required WebDavClient that,
    required String serverUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(serverUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiWebdavApiWebDavClientAutoAccessorSetServerUrlConstMeta,
        argValues: [that, serverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorSetServerUrlConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_set_server_url",
        argNames: ["that", "serverUrl"],
      );

  @override
  void crateApiWebdavApiWebDavClientAutoAccessorSetToken({
    required WebDavClient that,
    required String token,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(token, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWebdavApiWebDavClientAutoAccessorSetTokenConstMeta,
        argValues: [that, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorSetTokenConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_set_token",
        argNames: ["that", "token"],
      );

  @override
  void crateApiWebdavApiWebDavClientAutoAccessorSetUsername({
    required WebDavClient that,
    required String username,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiWebdavApiWebDavClientAutoAccessorSetUsernameConstMeta,
        argValues: [that, username],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientAutoAccessorSetUsernameConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_auto_accessor_set_username",
        argNames: ["that", "username"],
      );

  @override
  Future<List<WebDavEntry>> crateApiWebdavApiWebDavClientListAllAudioRecursive({
    required WebDavClient that,
    required String rootPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_web_dav_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavApiWebDavClientListAllAudioRecursiveConstMeta,
        argValues: [that, rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWebdavApiWebDavClientListAllAudioRecursiveConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_list_all_audio_recursive",
        argNames: ["that", "rootPath"],
      );

  @override
  Future<List<WebDavEntry>> crateApiWebdavApiWebDavClientListDirectory({
    required WebDavClient that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_web_dav_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavApiWebDavClientListDirectoryConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavApiWebDavClientListDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_list_directory",
        argNames: ["that", "path"],
      );

  @override
  WebDavClient crateApiWebdavApiWebDavClientNew({
    required String serverUrl,
    required String username,
    required String token,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverUrl, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(token, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWebdavApiWebDavClientNewConstMeta,
        argValues: [serverUrl, username, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavApiWebDavClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_new",
        argNames: ["serverUrl", "username", "token"],
      );

  @override
  BigInt crateApiSimpleAdd({required BigInt left, required BigInt right}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(left, serializer);
          sse_encode_u_64(right, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAddConstMeta,
        argValues: [left, right],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAddConstMeta =>
      const TaskConstMeta(debugName: "add", argNames: ["left", "right"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioPlayer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioPlayer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WebDavClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WebDavClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient;

  @protected
  AudioPlayer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioPlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioPlayer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioPlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WebDavEntry> dco_decode_list_web_dav_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_web_dav_entry).toList();
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PlaybackDiagnostics dco_decode_playback_diagnostics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PlaybackDiagnostics(
      path: dco_decode_String(arr[0]),
      streamOpenFilename: dco_decode_String(arr[1]),
      fileError: dco_decode_String(arr[2]),
      pausedForCache: dco_decode_bool(arr[3]),
      idleActive: dco_decode_bool(arr[4]),
      eofReached: dco_decode_bool(arr[5]),
      durationMs: dco_decode_i_64(arr[6]),
      positionMs: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  PlaybackProgress dco_decode_playback_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlaybackProgress(
      positionMs: dco_decode_i_64(arr[0]),
      durationMs: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PlaybackState_Stopped();
      case 1:
        return PlaybackState_Playing();
      case 2:
        return PlaybackState_Paused();
      case 3:
        return PlaybackState_Error(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TrackInfo dco_decode_track_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return TrackInfo(
      title: dco_decode_String(arr[0]),
      subtitle: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      albumArtist: dco_decode_String(arr[3]),
      album: dco_decode_String(arr[4]),
      genre: dco_decode_String(arr[5]),
      date: dco_decode_String(arr[6]),
      trackNumber: dco_decode_String(arr[7]),
      discNumber: dco_decode_String(arr[8]),
      lyrics: dco_decode_String(arr[9]),
      coverArt: dco_decode_opt_list_prim_u_8_strict(arr[10]),
      durationMs: dco_decode_i_64(arr[11]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WebDavEntry dco_decode_web_dav_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return WebDavEntry(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isDir: dco_decode_bool(arr[2]),
      size: dco_decode_u_64(arr[3]),
      lastModified: dco_decode_String(arr[4]),
      title: dco_decode_String(arr[5]),
      artist: dco_decode_String(arr[6]),
      album: dco_decode_String(arr[7]),
      durationMs: dco_decode_u_64(arr[8]),
    );
  }

  @protected
  AudioPlayer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioPlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioPlayer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioPlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WebDavEntry> sse_decode_list_web_dav_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WebDavEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_web_dav_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackDiagnostics sse_decode_playback_diagnostics(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_streamOpenFilename = sse_decode_String(deserializer);
    var var_fileError = sse_decode_String(deserializer);
    var var_pausedForCache = sse_decode_bool(deserializer);
    var var_idleActive = sse_decode_bool(deserializer);
    var var_eofReached = sse_decode_bool(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_positionMs = sse_decode_i_64(deserializer);
    return PlaybackDiagnostics(
      path: var_path,
      streamOpenFilename: var_streamOpenFilename,
      fileError: var_fileError,
      pausedForCache: var_pausedForCache,
      idleActive: var_idleActive,
      eofReached: var_eofReached,
      durationMs: var_durationMs,
      positionMs: var_positionMs,
    );
  }

  @protected
  PlaybackProgress sse_decode_playback_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_positionMs = sse_decode_i_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    return PlaybackProgress(
      positionMs: var_positionMs,
      durationMs: var_durationMs,
    );
  }

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return PlaybackState_Stopped();
      case 1:
        return PlaybackState_Playing();
      case 2:
        return PlaybackState_Paused();
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return PlaybackState_Error(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TrackInfo sse_decode_track_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_albumArtist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_trackNumber = sse_decode_String(deserializer);
    var var_discNumber = sse_decode_String(deserializer);
    var var_lyrics = sse_decode_String(deserializer);
    var var_coverArt = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    return TrackInfo(
      title: var_title,
      subtitle: var_subtitle,
      artist: var_artist,
      albumArtist: var_albumArtist,
      album: var_album,
      genre: var_genre,
      date: var_date,
      trackNumber: var_trackNumber,
      discNumber: var_discNumber,
      lyrics: var_lyrics,
      coverArt: var_coverArt,
      durationMs: var_durationMs,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WebDavEntry sse_decode_web_dav_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_lastModified = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    return WebDavEntry(
      path: var_path,
      name: var_name,
      isDir: var_isDir,
      size: var_size,
      lastModified: var_lastModified,
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationMs: var_durationMs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    AudioPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioPlayerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioPlayer(
    AudioPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioPlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_web_dav_entry(
    List<WebDavEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_web_dav_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_diagnostics(
    PlaybackDiagnostics self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.streamOpenFilename, serializer);
    sse_encode_String(self.fileError, serializer);
    sse_encode_bool(self.pausedForCache, serializer);
    sse_encode_bool(self.idleActive, serializer);
    sse_encode_bool(self.eofReached, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_i_64(self.positionMs, serializer);
  }

  @protected
  void sse_encode_playback_progress(
    PlaybackProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.positionMs, serializer);
    sse_encode_i_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PlaybackState_Stopped():
        sse_encode_i_32(0, serializer);
      case PlaybackState_Playing():
        sse_encode_i_32(1, serializer);
      case PlaybackState_Paused():
        sse_encode_i_32(2, serializer);
      case PlaybackState_Error(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_track_info(TrackInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.subtitle, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.albumArtist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.trackNumber, serializer);
    sse_encode_String(self.discNumber, serializer);
    sse_encode_String(self.lyrics, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.coverArt, serializer);
    sse_encode_i_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_web_dav_entry(WebDavEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.lastModified, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class AudioPlayerImpl extends RustOpaque implements AudioPlayer {
  // Not to be used by end users
  AudioPlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioPlayerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioPlayer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioPlayer,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioPlayerPtr,
  );
}

@sealed
class WebDavClientImpl extends RustOpaque implements WebDavClient {
  // Not to be used by end users
  WebDavClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WebDavClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WebDavClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WebDavClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WebDavClientPtr,
  );

  String get serverUrl => RustLib.instance.api
      .crateApiWebdavApiWebDavClientAutoAccessorGetServerUrl(that: this);

  String get token => RustLib.instance.api
      .crateApiWebdavApiWebDavClientAutoAccessorGetToken(that: this);

  String get username => RustLib.instance.api
      .crateApiWebdavApiWebDavClientAutoAccessorGetUsername(that: this);

  set serverUrl(String serverUrl) => RustLib.instance.api
      .crateApiWebdavApiWebDavClientAutoAccessorSetServerUrl(
        that: this,
        serverUrl: serverUrl,
      );

  set token(String token) =>
      RustLib.instance.api.crateApiWebdavApiWebDavClientAutoAccessorSetToken(
        that: this,
        token: token,
      );

  set username(String username) =>
      RustLib.instance.api.crateApiWebdavApiWebDavClientAutoAccessorSetUsername(
        that: this,
        username: username,
      );

  /// Recursively lists all entries under [root_path] using BFS PROPFIND.
  /// Only returns files (is_dir == false) that are audio files.
  Future<List<WebDavEntry>> listAllAudioRecursive({required String rootPath}) =>
      RustLib.instance.api.crateApiWebdavApiWebDavClientListAllAudioRecursive(
        that: this,
        rootPath: rootPath,
      );

  /// Lists a single directory (Depth: 1) via PROPFIND.
  /// Returns all immediate children (files and subdirs).
  Future<List<WebDavEntry>> listDirectory({required String path}) => RustLib
      .instance
      .api
      .crateApiWebdavApiWebDavClientListDirectory(that: this, path: path);
}
