// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'player_api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GLOBAL_SINK`, `HTTP_CLIENT`, `PLAYER_STATE`, `TrackInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioPlayer>>
abstract class AudioPlayer implements RustOpaqueInterface {
  static Future<PlaybackState> getState() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerGetState();

  static Future<PlaybackProgress> getProgress() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerGetProgress();

  /// Initializes the audio engine permanently in a background thread
  static Future<void> initEngine() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerInitEngine();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioPlayer> newInstance() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerNew();

  static Future<void> pause() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerPause();

  /// Plays a local file
  static Future<void> playLocalFile({required String path}) => RustLib
      .instance
      .api
      .crateApiPlayerApiAudioPlayerPlayLocalFile(path: path);

  /// Downloads a remote WebDAV audio file to a temp file and plays it.
  /// username / token are used for HTTP Basic Auth.
  static Future<void> playRemoteFile({
    required String url,
    required String username,
    required String token,
  }) => RustLib.instance.api.crateApiPlayerApiAudioPlayerPlayRemoteFile(
    url: url,
    username: username,
    token: token,
  );

  static Future<void> resume() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerResume();

  static Future<void> seek({required int positionMs}) =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerSeek(
        positionMs: BigInt.from(positionMs),
      );

  static Future<void> stop() =>
      RustLib.instance.api.crateApiPlayerApiAudioPlayerStop();
}

class PlaybackProgress {
  final int positionMs;
  final int durationMs;

  const PlaybackProgress({required this.positionMs, required this.durationMs});
}

@freezed
sealed class PlaybackState with _$PlaybackState {
  const PlaybackState._();

  const factory PlaybackState.stopped() = PlaybackState_Stopped;
  const factory PlaybackState.playing() = PlaybackState_Playing;
  const factory PlaybackState.paused() = PlaybackState_Paused;
  const factory PlaybackState.error(String field0) = PlaybackState_Error;
}
