// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `propfind`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebDavClient>>
abstract class WebDavClient implements RustOpaqueInterface {
  String get serverUrl;

  String get token;

  String get username;

  set serverUrl(String serverUrl);

  set token(String token);

  set username(String username);

  /// Recursively lists all entries under [root_path] using BFS PROPFIND.
  /// Only returns files (is_dir == false) that are audio files.
  Future<List<WebDavEntry>> listAllAudioRecursive({required String rootPath});

  /// Lists a single directory (Depth: 1) via PROPFIND.
  /// Returns all immediate children (files and subdirs).
  Future<List<WebDavEntry>> listDirectory({required String path});

  factory WebDavClient({
    required String serverUrl,
    required String username,
    required String token,
  }) => RustLib.instance.api.crateApiWebdavApiWebDavClientNew(
    serverUrl: serverUrl,
    username: username,
    token: token,
  );
}

class WebDavEntry {
  final String path;
  final String name;
  final bool isDir;
  final BigInt size;
  final String lastModified;

  const WebDavEntry({
    required this.path,
    required this.name,
    required this.isDir,
    required this.size,
    required this.lastModified,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified;
}
